export const SEARCH_GIPHY_BY_TERM = 'SEARCH_GIPHY_BY_TERM';
export const SET_IS_LOADING_STATUS = 'SET_IS_LOADING_STATUS';
export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const SEARCH_GIPHY_BY_TERM_COMPLETE = 'SEARCH_GIPHY_BY_TERM_COMPLETE';